---
- name: Install WordPress with LAMP stack
  hosts: webserver
  become: true

  vars:
    db_name: wp_db
    db_user: wp_user
    db_password: wp_password
    wp_title: My WordPress Site
    wp_admin_user: admin
    wp_admin_password: admin_password

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and modules
      apt:
        name:
          - libapache2-mod-php
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
        state: present

    
    - name: Create a MySQL user for WordPress
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "{{ db_password }}"

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: true
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Configure WordPress
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure Apache virtual host for WordPress
      template:
        src: templates/wordpress.conf.j2
        dest: /etc/apache2/sites-available/wordpress.conf
      become: true
    - name: Enable Apache virtual host for WordPress
      apache2_module:
        name: rewrite
        state: present
      become: true
    - name: Enable Apache virtual host for WordPress
      apache2_site:
        name: wordpress
        state: present
      become: true

  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
